data_directory: "../data/output-XETG00171__0050702__Region_2__20250606__163112"
output_directory: "../output/output-XETG00171__0050702__Region_2__20250606__163112"
annotation_model: "llama3.1:8b"

pipeline:
  minimum_counts: 200
  maximum_counts_quantile: 0.99
  minimum_cells: 100
  pca_n_components: 30
  neighborhood_radius: 50.0
  colocalization_radius: 20.0
  colocalization_number_of_permutations: 1000
  colocalization_minimum_cells: 30
  domain_n_clusters: 8
  rank_top_n: 30
  minimum_logarithm_fold_change: 0.5
  maximum_adjusted_p_value: 0.05

plots:
  genes_to_plot: ["TUBB", "CDH1"]
